### ISSUE TITLE
Yammer no longer raise Unauthorized, instead returns string "Authenticated Failure"

### ISSUE THREAD

**Issue by synth** [yammer/yam#34]
Its our understanding the yam gem should raise an Unauthorized exception when a request is made that is, um, unauthorized.  

However, we've noticed recently that unauthorized requests are just return the string "Authenticated Failure" which is wrong because a) its not valid json b) it should be raising an exception.

Looking through the codebase, it looks like the only reference to Unauthorized is in error.rb#from_status method which I don't see being called from anywhere.

What is the proper way to handle unauthorized requests?

**Comment by alexspeller** [comment]
I am experiencing this too.

```ruby
Yammer::Client.new.all_users
```

This should definitely raise an exception, it's pretty insane to return a string and have to inspect the type of the response to see if it worked or not.

**Comment by robertIngrum** [comment]
Is this gem just abandoned?  This seems like a fairly important issue that still hasn't been addressed.

**Comment by mrbriandavis** [comment]
@robertIngrum - This is a painful issue that I am going to take a look to fix soon.

**Comment by chrisbloom7** [comment]
This seems to be affecting `Yammer::Resources::User.current`, even when `Yammer::Client#current_user` works ok:

```ruby
client = Yammer::Client.new(access_token: access_token)
# => #<Yammer::Client:0x007fe8e3257b18
#  @access_token="[REDACTED]",
#  @client_id="[REDACTED]",
#  @client_secret="[REDACTED]",
#  @connection_options={:max_redirects=>5, :verify_ssl=>true, :use_ssl=>true},
#  @default_headers={"Accept"=>"application/json", "User-Agent"=>"Yammer Ruby Gem 2.5.0"},
#  @http_adapter=Yammer::HttpAdapter,
#  @site_url="https://www.yammer.com">
client.current_user
# => #<Yammer::ApiResponse:0x007fe8e40460f8
#  @body=
#   "{\"type\":\"user\",\"id\":[REDACTED],\"network_id\":[REDACTED], ...}",
#  @code=200,
#  @headers=
#   {:status=>"200 OK", ...}>
client.current_user.code
# => 200
Yammer::Resources::User.current
Exception: NoMethodError: undefined method `success?' for "Authentication failure.":String
Did you mean?  succ!
--
0: /Users/chrisbloom/.rvm/gems/ruby-2.3.1@rails/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:76:in `method_missing'
1: /Users/chrisbloom/.rvm/gems/ruby-2.3.1@rails/gems/yam-2.5.0/lib/yammer/resources/user.rb:22:in `current'
```

**Comment by IMhide** [comment]
3 years after, this issue is still goin
